name: nosk
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cloudinary: ^1.2.0
  dio: ^5.8.0+1
  copy_with_extension: ^6.0.0
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  google_fonts: ^6.2.1
  file_picker: ^9.0.2
  path_provider: ^2.1.5
  firebase_app_check: ^0.3.2+4
  url_launcher: ^6.3.1
  extension_helpers:
  animations: ^2.0.11
  badges: ^3.1.2
  intl: ^0.20.2
  connectivity_plus: ^6.1.2
  cached_network_image: ^3.4.1
  chopper: ^8.0.4
  equatable: ^2.0.7
  faker: ^2.2.0
  flutter_svg: ^2.0.17
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_storage: ^12.4.4
  validatorless: ^1.2.4
  responsive_framework: ^1.5.1
  pinput: ^5.0.1
  smart_auth: ^3.2.0
  heroicons: ^0.11.0
  retry: ^3.1.2
  shimmer: ^3.0.0
  responsive_sizer: ^3.3.1
  tinycolor2: ^3.0.1
  smooth_page_indicator: ^1.2.0+3
  wakelock_plus: ^1.2.10
  upgrader: ^11.3.1
  json_annotation: ^4.9.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  chopper_generator: ^8.0.4
  copy_with_extension_gen: ^6.0.0
  json_serializable: ^6.9.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  #  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/

dependency_overrides:
  extension_helpers:
    path: extension_helpers
