// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXl9Ds8DBWAn6jSy2BRPYInsFB9VkI4m4',
    appId: '1:214623807126:android:a30f85938be75c2e8304b7',
    messagingSenderId: '214623807126',
    projectId: 'nosk-classic',
    storageBucket: 'nosk-classic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFLYE12FgpmmrInl_OAsc-z11MyEruElA',
    appId: '1:214623807126:ios:ba80f6206b1f6bd48304b7',
    messagingSenderId: '214623807126',
    projectId: 'nosk-classic',
    storageBucket: 'nosk-classic.firebasestorage.app',
    iosClientId: '214623807126-6o61d2onsj4j58t91ohchohqcclb75a5.apps.googleusercontent.com',
    iosBundleId: 'com.codeblock.nosk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFLYE12FgpmmrInl_OAsc-z11MyEruElA',
    appId: '1:214623807126:ios:ba80f6206b1f6bd48304b7',
    messagingSenderId: '214623807126',
    projectId: 'nosk-classic',
    storageBucket: 'nosk-classic.firebasestorage.app',
    iosClientId: '214623807126-6o61d2onsj4j58t91ohchohqcclb75a5.apps.googleusercontent.com',
    iosBundleId: 'com.codeblock.nosk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARoH6vIw8ROEecSLPz9dPJsVGvo2F0jpo',
    appId: '1:214623807126:web:7e0c084f2a4d44bd8304b7',
    messagingSenderId: '214623807126',
    projectId: 'nosk-classic',
    authDomain: 'nosk-classic.firebaseapp.com',
    storageBucket: 'nosk-classic.firebasestorage.app',
    measurementId: 'G-NE4SF45KV8',
  );
}